# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: assesuser
      POSTGRES_PASSWORD: assesuser
      POSTGRES_DB: assesbackend
    volumes:
       - ./data:/var/lib/postgresql/data
    ports:
       - "5432:5432"